# This is a basic workflow to help you get started with Actions

name: Build GCC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     
    - name: Install GCC
      run:   |
        sudo apt update
        sudo apt install gcc-10 g++-10
      
    - name: Build Demo
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: gcc demo.cpp -std=c++20 

