# This is a basic workflow to help you get started with Actions

name: Build GCC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
           
    - name: Update GCC
      run: apt install gcc
        
           
    - name: Build Demo
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: g++ demo.cpp -std=gnu++2a

